name: GitHub Actions CI build
run-name: ${{ github.actor }} use GitHub Actions for CI build
on: [push]
jobs:
  GitHub-Actions-CI-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          echo "Repository: ${{ github.repository }}, branch: ${{ github.ref }}"
      - run: |
          echo "Running on: ${{ runner.os }}, triggered by: ${{ github.event_name }}"
      # - name: Update distro
      #   run: sudo apt update
      # - name: Upgrade distro
      #   run: sudo apt upgrade
      - name: Install deps
        run: sudo apt install libiniparser-dev libsdl2-dev ;
             sudo apt install 7zip genisoimage grep tar wget
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build ci
        run: cd src ; make ci
      - name: List files in the repository
        run: ls -l ${{ github.workspace }}/.. ;
             ls -l ${{ github.workspace }} ;
             ls -l ${{ github.workspace }}/src
      - name: Get date
        run: |
             export DATE=`date -I` ;
             echo "DATE: ${{ DATE }}"
       - name: Reset ci-latest tag
        run: |
          # VERSION=${{ steps.version_number.outputs.version }}
          git config --global user.email "ci@github.com"
          git config --global user.name "Github CI"
          git tag -d ci-latest       || true
          git push origin :ci-latest || true
          git tag -m ci-latest ci-latest
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create CI rel
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          draft: false
          name: CI Build
          tag: ci-latest
          prerelease: true
          replacesArtifacts: true
          artifacts: "
            ../powerBudget00001a_${DATE}_Linux_x86_64_64bit.tgz,
            ../powerBudget00001a_${DATE}_Linux_x86_64_64bit.AppImage
          "
      - run: |
          echo "End status: ${{ job.status }}"
