name: GitHub Actions CI build
run-name: ${{ github.actor }} use GitHub Actions for CI build
on: [push]
jobs:
  GitHub-Actions-CI-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository ${{ github.repository }}, branch ${{ github.ref }}"
      - run: echo "Running on ${{ runner.os }}, triggered by ${{ github.event_name }}"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt install libiniparser-dev libsdl2-dev |
             sudo apt install 7zip genisoimage grep tar wget
      - name: List files in the repository
        run: ls -l ${{ github.workspace }}
      - name: Build rel
        run: cd src ; make force
      - name: List files in the repository
        run: ls -l ${{ github.workspace }}
      - run: echo "End status ${{ job.status }}."
